// src/components/home-page/Foot.jsx
import '../../assets/Style/Footer.css';
import AnimatedContent from '../other-function/AnimatedContent';

import React from 'react';
import { useTranslation } from '../other-function/TranslationList';

const Foot = () =>{
    const {translations, language} = useTranslation();
    return(
        <div className="flex foot tx-c flex-column">
            <AnimatedContent>
                <div className='p-2 flex flex-column'>
                    <p>{translations[language].footer}</p>
                    <p className="f-30 flex space-between">pencibambo@gmail.com
                    </p>
                </div>
            </AnimatedContent>
        </div>
    )
}

export default Foot;

// src/components/small_components/Foot.vue
<template>
    <div class="flex foot tx-c flex-column">
        <AnimatedContent>
            <div class='p-2 flex flex-column'>
                <p>{{translations.footer}}</p>
                <p class="f-30 flex space-between">pencibambo@gmail.com</p>
            </div>
        </AnimatedContent>
    </div>
</template>

<script>
import { mapGetters } from 'vuex/dist/vuex.common.js';
import AnimatedContent from '../function_components/AnimatedContent.vue';

export default{
    components:{AnimatedContent},
    computed:{
        ...mapGetters(['translations'])
    }
}
</script>
